const { pool } = require('../config/db');
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');

exports.reportsPage = async (req, res) => {
  try {
    const [appointments] = await pool.query('SELECT COUNT(*) AS count FROM appointments');
    const [completed] = await pool.query("SELECT COUNT(*) AS count FROM appointments WHERE status = 'Completed'");
    const [patients] = await pool.query('SELECT COUNT(*) AS count FROM patients');
    const [inventory] = await pool.query('SELECT SUM(quantity) AS total FROM inventory');

    res.render('reports/index', {
      user: req.session.user,
      stats: {
        appointments: appointments[0].count,
        completed: completed[0].count,
        patients: patients[0].count,
        inventory: inventory[0].total || 0
      }
    });
  } catch (error) {
    console.error(error);
    res.status(500).render('error', { message: 'Reports error', user: req.session.user });
  }
};

exports.exportPdf = async (req, res) => {
  try {
    const [appointments] = await pool.query('SELECT COUNT(*) AS count FROM appointments');
    const [completed] = await pool.query("SELECT COUNT(*) AS count FROM appointments WHERE status = 'Completed'");
    const [patients] = await pool.query('SELECT COUNT(*) AS count FROM patients');
    const [inventory] = await pool.query('SELECT SUM(quantity) AS total FROM inventory');

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="reports.pdf"');
    doc.pipe(res);

    doc.fontSize(20).text('Dental Clinic Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Total Appointments: ${appointments[0].count}`);
    doc.text(`Completed Appointments: ${completed[0].count}`);
    doc.text(`New Patients: ${patients[0].count}`);
    doc.text(`Inventory Usage (total qty): ${inventory[0].total || 0}`);
    doc.moveDown();

    doc.text('Generated by: ' + (req.session.user ? req.session.user.name : 'system'));
    doc.text('Generated at: ' + new Date().toLocaleString());

    doc.end();

    // audit log
    await pool.query('INSERT INTO audit_logs (user_id, action, details) VALUES (?, ?, ?)', [req.session.user ? req.session.user.id : null, 'export_pdf', 'Exported reports to PDF']);
  } catch (error) {
    console.error(error);
    res.status(500).render('error', { message: 'Export PDF error', user: req.session.user });
  }
};

exports.exportExcel = async (req, res) => {
  try {
    const [appointments] = await pool.query('SELECT * FROM appointments ORDER BY appointment_date DESC');
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Appointments');

    sheet.columns = [
      { header: 'ID', key: 'id', width: 8 },
      { header: 'Patient ID', key: 'patient_id', width: 12 },
      { header: 'Title', key: 'title', width: 30 },
      { header: 'Date', key: 'appointment_date', width: 20 },
      { header: 'Status', key: 'status', width: 12 }
    ];

    appointments.forEach(a => {
      sheet.addRow({ id: a.id, patient_id: a.patient_id, title: a.title, appointment_date: a.appointment_date, status: a.status });
    });

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename="appointments.xlsx"');
    await workbook.xlsx.write(res);
    res.end();

    await pool.query('INSERT INTO audit_logs (user_id, action, details) VALUES (?, ?, ?)', [req.session.user ? req.session.user.id : null, 'export_excel', 'Exported appointments to Excel']);
  } catch (error) {
    console.error(error);
    res.status(500).render('error', { message: 'Export Excel error', user: req.session.user });
  }
};
